export const ADMIN_MESSAGES = 'ADMIN_MESSAGES';
export const CHATMESSAGES = 'CHAT_MESSAGES';
export const TICKETREQUESTMESSAGES = 'TICKETREQUEST_MESSAGES';
export const TICKETRAISEDMESSAGES = 'TICKETRAISED_MESSAGES';
